import type { Metadata } from "next";
import { Inter,JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairEffects from "@/components/StairEffects";
const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"],
weight:["100","200","300","400","500","600","700","800"],
variable:"--font-jetbrainsMono" });

export const metadata: Metadata = {
  title: "Cangan Cynthia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.className}>
        <Header/>
        <StairEffects/>
        <PageTransition>
        

        {children}
        </PageTransition>
      </body>
    </html>
  );
}
